// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Streamflix.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208144002_ViewingHistoryManyToOne")]
    partial class ViewingHistoryManyToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentId"));

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("AvailableQualities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("ContentWarnings")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WatchlistId")
                        .HasColumnType("integer");

                    b.HasKey("ContentId");

                    b.HasIndex("WatchlistId");

                    b.ToTable("Contents");

                    b.HasDiscriminator().HasValue("Content");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EpisodeId"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EpisodeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("AgeCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProfileId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.ProfilePreference", b =>
                {
                    b.Property<int>("ProfilePreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfilePreferenceId"));

                    b.PrimitiveCollection<List<string>>("ContentFilters")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("PreferredGenres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("ProfilePreferenceId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ProfilePreferences");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonId"));

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.ViewingHistory", b =>
                {
                    b.Property<int>("ViewingHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ViewingHistoryId"));

                    b.Property<int>("ContentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LastPosition")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ViewingHistoryId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ViewingHistories");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Watchlist", b =>
                {
                    b.Property<int>("WatchlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WatchlistId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("WatchlistId");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Movie", b =>
                {
                    b.HasBaseType("Streamflix.Infrastructure.Entities.Content");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Series", b =>
                {
                    b.HasBaseType("Streamflix.Infrastructure.Entities.Content");

                    b.Property<int>("TotalSeasons")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Series");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Content", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Watchlist", null)
                        .WithMany("Content")
                        .HasForeignKey("WatchlistId");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Episode", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.ProfilePreference", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Profile", "Profile")
                        .WithOne("Preference")
                        .HasForeignKey("Streamflix.Infrastructure.Entities.ProfilePreference", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Season", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.ViewingHistory", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Profile", "Profile")
                        .WithMany("ViewingHistories")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Watchlist", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Profile", "Profile")
                        .WithOne("Watchlist")
                        .HasForeignKey("Streamflix.Infrastructure.Entities.Watchlist", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Profile", b =>
                {
                    b.Navigation("Preference");

                    b.Navigation("ViewingHistories");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Watchlist", b =>
                {
                    b.Navigation("Content");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Series", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
