// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Streamflix.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122164538_UpdateDomain")]
    partial class UpdateDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentContentWarning", b =>
                {
                    b.Property<int>("ContentWarningsContentWarningId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentsContentId")
                        .HasColumnType("integer");

                    b.HasKey("ContentWarningsContentWarningId", "ContentsContentId");

                    b.HasIndex("ContentsContentId");

                    b.ToTable("ContentContentWarnings", (string)null);
                });

            modelBuilder.Entity("ContentQuality", b =>
                {
                    b.Property<int>("AvailableQualitiesQualityId")
                        .HasColumnType("integer");

                    b.Property<int>("ContentsContentId")
                        .HasColumnType("integer");

                    b.HasKey("AvailableQualitiesQualityId", "ContentsContentId");

                    b.HasIndex("ContentsContentId");

                    b.ToTable("ContentQualities", (string)null);
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Content", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentId"));

                    b.Property<int>("AgeRating")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ContentId");

                    b.HasIndex("GenreId");

                    b.ToTable("Contents");

                    b.HasDiscriminator().HasValue("Content");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.ContentWarning", b =>
                {
                    b.Property<int>("ContentWarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ContentWarningId"));

                    b.Property<int>("ContentWarningType")
                        .HasColumnType("integer");

                    b.HasKey("ContentWarningId");

                    b.ToTable("ContentWarnings");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EpisodeId"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EpisodeId");

                    b.HasIndex("SeasonId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<int>("GenreType")
                        .HasColumnType("integer");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Quality", b =>
                {
                    b.Property<int>("QualityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QualityId"));

                    b.Property<int>("QualityType")
                        .HasColumnType("integer");

                    b.HasKey("QualityId");

                    b.ToTable("Qualities");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonId"));

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Movie", b =>
                {
                    b.HasBaseType("Streamflix.Infrastructure.Entities.Content");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Series", b =>
                {
                    b.HasBaseType("Streamflix.Infrastructure.Entities.Content");

                    b.Property<int>("TotalSeasons")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Series");
                });

            modelBuilder.Entity("ContentContentWarning", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.ContentWarning", null)
                        .WithMany()
                        .HasForeignKey("ContentWarningsContentWarningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamflix.Infrastructure.Entities.Content", null)
                        .WithMany()
                        .HasForeignKey("ContentsContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContentQuality", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Quality", null)
                        .WithMany()
                        .HasForeignKey("AvailableQualitiesQualityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Streamflix.Infrastructure.Entities.Content", null)
                        .WithMany()
                        .HasForeignKey("ContentsContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Content", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Genre", "Genre")
                        .WithMany("Contents")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Episode", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Season", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Season", b =>
                {
                    b.HasOne("Streamflix.Infrastructure.Entities.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Genre", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Season", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("Streamflix.Infrastructure.Entities.Series", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
